WebApplication2/Controllers/GamesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class GamesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Games
        public ActionResult Index()
        {
            return View(db.Games.ToList());
        }

        // GET: Games/Details/5
        public ActionResult Recenzii(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Game game = db.Games.Find(id);
            if (game == null)
            {
                return HttpNotFound();
            }
            return View(game);
        }

        // GET: Games/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Games/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Slika,Ime,Opis,Ocena,Recenz,Poster,GameplaySlika")] Game game)
        {
            if (ModelState.IsValid)
            {
                db.Games.Add(game);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(game);
        }

        // GET: Games/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Game game = db.Games.Find(id);
            if (game == null)
            {
                return HttpNotFound();
            }
            return View(game);
        }

        // POST: Games/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Slika,Ime,Opis,Ocena,Recenz,Poster,GameplaySlika")] Game game)
        {
            if (ModelState.IsValid)
            {
                db.Entry(game).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(game);
        }

        // GET: Games/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Game game = db.Games.Find(id);
            if (game == null)
            {
                return HttpNotFound();
            }
            return View(game);
        }

        // POST: Games/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Game game = db.Games.Find(id);
            db.Games.Remove(game);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication2/Controllers/NovostsController.cs
    using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class NovostsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Novosts
        public ActionResult Index()
        {
            return View(db.Novosts.ToList());
        }

        // GET: Novosts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Novost novost = db.Novosts.Find(id);
            if (novost == null)
            {
                return HttpNotFound();
            }
            return View(novost);
        }

        // GET: Novosts/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Novosts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Slika,Naslov,Kratko,Storija")] Novost novost)
        {
            if (ModelState.IsValid)
            {
                db.Novosts.Add(novost);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(novost);
        }

        // GET: Novosts/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Novost novost = db.Novosts.Find(id);
            if (novost == null)
            {
                return HttpNotFound();
            }
            return View(novost);
        }

        // POST: Novosts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Slika,Naslov,Kratko,Storija")] Novost novost)
        {
            if (ModelState.IsValid)
            {
                db.Entry(novost).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(novost);
        }

        // GET: Novosts/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Novost novost = db.Novosts.Find(id);
            if (novost == null)
            {
                return HttpNotFound();
            }
            return View(novost);
        }

        // POST: Novosts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Novost novost = db.Novosts.Find(id);
            db.Novosts.Remove(novost);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <style>
        #logoto {
            height: 90px;
            width: 196px;
            background: url('../../Sliki/Screenshot_2.png');
        }

        #logoto:hover {
            height: 90px;
            width: 196px;
            background: url('../../Sliki/Screenshot_2 - Copy.png');
           
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" style="background: rgba(255,255,255,1)">
        <div class="container">
            <div class="navbar-header">
                <a href="@Url.Action("Index","Home")"><div id="logoto"></div></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="btn btn-default" style="margin-top:15px;padding:5px;margin-left:30px;font-size:20px;background: linear-gradient(white,lightgrey);">@Html.ActionLink("Игри", "Index", "Games")</li>
                    <li class="btn btn-default" style="margin-top:15px;padding:5px;margin-left:25px;font-size:20px;background: linear-gradient(white,lightgrey)">@Html.ActionLink("Новости", "Index", "Novosts")</li>
                    @if (User.Identity.IsAuthenticated)
                    {
                    <li class="btn btn-default" style="margin-top:15px;padding:5px;margin-left:25px;font-size:20px;background: linear-gradient(white,lightgrey)">@Html.ActionLink("Додади корисник", "Register", "Account")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        <hr />
        <hr />
        @RenderBody()
        <hr />
    </div>
    <footer style="background-color:grey;width:100%;text-align:center">
        <p style="color:azure;font-size:20px">163136 - Ѓорге Гогов</p>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>